// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh routes`.

import * as $0 from "./pages/api/joke.ts";
import * as $1 from "./pages/index.tsx";
import * as $2 from "./pages/[name].tsx";

const routes = {
  pages: {
    "./pagesnt/pages/api/joke.ts": $0,
    "./pagesnt/pages/index.tsx": $1,
    "./pagesnt/pages/[name].tsx": $2,
  },
  baseUrl: import.meta.url,
};

export default routes;
